Nama = input("Masukkan Nama Anda: ")
NIM = input("Masukkan NIM Anda: ")
kelas = input("Masukkan Kelas Anda: ")
ttl = input("Masukkan Tempat Tanggal Lahir Anda: ")
alamat = input("Masukkan Alamat Anda: ")
hobi = input("Masukkan Hobi Anda: ")
no_hp = input("Masukkan Nomor HP Anda: ")

print(f"Nama: {Nama}")
print(f"NIM: {NIM}")
print(f"Kelas: {kelas}")
print(f"Tempat Tanggal Lahir: {ttl}")
print(f"Alamat: {alamat}")
print(f"Hobi: {hobi}")
print(f"Nomor HP: {no_hp}")
